### ISSUE TITLE
xDSL driver version not updated on Card

### ISSUE THREAD

**Issue by ettoremazza** [Ansuel/tch-nginx-gui#318]
Card shows old selected driver, even after reboot.

DGA4130
8.8.77
1.1.1

https://www.dropbox.com/s/85frokkmt2925im/Screenshot%202018-10-30%2016.56.08.png?dl=0

**Comment by Ansuel** [comment]
are you sure you have that driver?

**Comment by Janaue** [comment]
Do you talk about the different names for '''Firmware Version'' and ''Driver Version'' ?

If so, I have this too. THe '''Firmware Version'' is the original adsl driver by the original Telstra firmware, ending in 26q. THen I can select a driver version, but the two names are always different, since ''Driver Version'' has no driver ending in 26q
![sshot-132](https://user-images.githubusercontent.com/10972636/47767151-9c666800-dcd2-11e8-9315-f122b2446755.jpg)

**Comment by Ansuel** [comment]
umm yes i should really rename the driver... 

d26r (or m) is another part of the driver (the version of the kernel module) the problem is that i change only the adsl bin and not the kernel module (due to compaitiblity reason...)

anyway i love the dslam with non standard firmware version ahahah
