### ISSUE TITLE
WARNING - Ansuel/tch-nginx-gui DEV WILL BRICK YOUR GATEWAY

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#473]
Model: TG799vac

https://forums.whirlpool.net.au/thread/2650998?p=170#r3395

https://github.com/Ansuel/tch-nginx-gui/issues/469#issuecomment-462009326

Looks like issue has been going for a while but current stable is OK.

**Comment by kevdagoat** [comment]
Do not set it to dev mode. You will brick your modem!!!

**Comment by nutterpc** [comment]
Lemme see what I can do

**Comment by Ansuel** [comment]
Will work on a slimmed version of the GUI...

The GUI is big because of the tmp zip...
Also in rootdevice there is a check for the space but looks like it does brick also with 95% space....
We can't really do much about this... Technicolor didn't add any check about this... They also disabled failsafe... The check should be done in preinit before mount of overlay...

**Comment by flywire** [comment]
[TG799_putty.log](https://pastebin.com/bm59AkXB)

> [    8.355000] init: - preinit -
>
>[    9.984000] jffs2: notice: (260) jffs2_build_xattr_subsystem: complete building xattr subsystem, 4 of xdatum (4 unchecked, 0 orphan) and 580 of xref (0 dead, 454 orphan) found.

**Comment by FrancYescO** [comment]
conntinue discussion here https://github.com/Ansuel/tch-nginx-gui/issues/469

https://github.com/Ansuel/tch-nginx-gui/commit/b273e6f6c852b44f23ca1c94282ba6633643d934 should have fixed
