### ISSUE TITLE
wifi button does nto work tg800 16.2 gui 9.0.90

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#623]
My wifi button does not work at all, either to turn ON or OFF. I need to go the GUI, then click On or OFF for the 5ghz and the 2,4 ghz. I also enable band steering, so that on the stock GUI, the 2,4ghz and 5ghz are turned OFF or ON at the same time, here they are independant.

ECO LED is OFF

also, my power button is BLUE, not GREEN 💃

**Comment by kevdagoat** [comment]
Post /etc/config/button

From: Janaue
Sent: Monday, April 8, 2019 12:23 AM
To: Ansuel/tch-nginx-gui
Cc: Subscribed
Subject: [Ansuel/tch-nginx-gui] wifi button does nto work tg800 16.2 gui9.0.90 (#623)

My wifi button does not work at all, either to turn ON or OFF. I need to go the GUI, then click On or OFF for the 5ghz and the 2,4 ghz. I also enable band steering, so that on the stock GUI, the 2,4ghz and 5ghz are turned OFF or ON at the same time, here they are independant.

**Comment by FrancYescO** [comment]
Issuing `wifionoff.sh` from ssh is working the toggle WiFi?
Power led is blue only when WiFi off?

**Comment by FrancYescO** [comment]
News?

**Comment by kevdagoat** [comment]
@francyesco the user hasn’t reported anything else yet.

**Comment by FrancYescO** [comment]
This is why I'm asking for news.

**Comment by kevdagoat** [comment]
@francyesco Yes I know
