### ISSUE TITLE
add another branch called dev and rename master branch

### ISSUE THREAD

**Issue by nutterthanos** [Ansuel/tch-nginx-gui#695]
Hello I was wondering since you started doing a preview version besides the stable and dev version that you will change the master branch to preview since the commits on the master branch say Preview and start a branch that’s called dev unless it’s fine as it currently is.

**Comment by FrancYescO** [comment]
done https://github.com/Ansuel/tch-nginx-gui/commit/822e688f176b4ca2eea4bbdbb5b53ab06295fb67

**Comment by nutterthanos** [comment]
Well now it seems that there is the same commits done on both branch’s master and dev.

**Comment by Ansuel** [comment]
Actually now
Dev is master
Preview Is preview
Stanze Is stable

When something is enough stable, Dev commits are merged to preview

Preview build are Dev builds with stripped down files. Because of this,
debug problems in a preview build is nearly impossible. In short... Preview
= testing stable

We can't change master to Dev as master in a GitHub repo is standard and
would complicate things. Any question?

Il Sab 6 Lug 2019, 02:38 nutterthanos <notifications@github.com> ha scritto:
